#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Pin which SDK getter fills every message and point field, for every model.

The probe (generated by stream_mapping/generate_probe.py) runs the stream codecs
on mocked SDK lists whose getters return distinct codes. Decoded, the output is
compared with stream_mapping/expected_mapping.json, which was produced from the
per-model callbacks before they were replaced by the templated codecs.
Regenerate after an intended change with: test_stream_mapping.py --write
"""

import json
import math
import os
from pathlib import Path
import struct
import subprocess
import sys

import yaml

EXPECTED = Path(__file__).resolve().parent / 'stream_mapping' / 'expected_mapping.json'
MAXIMA = {255, 65535, 4294967295}


def f32(value):
    return struct.unpack('<f', struct.pack('<f', value))[0]


DEG = f32(math.pi / 180.0)


def decoder(codes, namespace):
    table = {}
    for key, entry in codes.items():
        if key.startswith(namespace + '/'):
            for getter, code in entry['codes'].items():
                table[code] = entry['role'] + '.' + getter

    def decode(value):
        if value is True:
            return 'true'
        if value == 'nan':
            return 'nan'
        if value in (0, 0.0, False):
            return None
        if value in MAXIMA:
            return 'max'
        if value in table:
            return table[value]
        code = round(value / DEG)
        if code in table and f32(code * DEG) == value:
            return table[code] + '*deg2rad'
        return 'unknown:%r' % value
    return decode


def decode_case(result, decode):
    fields = {}
    header = yaml.safe_load(result['header'])
    header.pop('header', None)
    reports = header.pop('reports', None)
    header = header.pop('fault_report_header', header)
    for key, value in header.items():
        fields['header.' + key] = decode(value)
    for key, value in (reports[0] if reports else {}).items():
        fields['report.' + key] = decode(value)
    raw = yaml.safe_load(result['raw'])
    for key in ('false_alarm_probability_raw', 'flags_raw'):
        fields['raw.' + key] = decode(raw[key][0]) if raw[key] else None
    cloud = result.get('cloud')
    if cloud is not None:
        assert len(cloud) == 2, 'expected one point per mocked item'
        point = cloud[0]
        for key, value in point.items():
            fields['point.' + key] = decode(value)
        if 'radial_speed' in point:
            rng, elevation, azimuth = (f32(point[k]) for k in (
                'range', 'elevation_angle', 'azimuth_angle'))
            planar = f32(rng * f32(math.cos(elevation)))
            expected = {'x': f32(planar * f32(math.cos(azimuth))),
                        'y': f32(planar * f32(math.sin(azimuth))),
                        'z': f32(rng * f32(math.sin(elevation))),
                        'snr': f32(point['power'] - point['noise'])}
            for key, value in expected.items():
                assert math.isclose(point[key], value, rel_tol=1e-5, abs_tol=1e-5), key
                fields['point.' + key] = 'computed'
    return {key: value for key, value in fields.items() if value is not None}


def decoded_mapping():
    probe = os.environ['SMARTMICRO_STREAM_PROBE']
    meta = json.loads(Path(os.environ['SMARTMICRO_STREAM_CODES']).read_text())
    output = json.loads(subprocess.run([probe], check=True, capture_output=True,
                                       text=True).stdout)
    assert set(output) == set(meta['cases'])
    return {case: decode_case(result, decoder(meta['codes'], meta['cases'][case]))
            for case, result in sorted(output.items())}


def test_stream_mapping_matches_reference():
    expected = json.loads(EXPECTED.read_text())
    actual = decoded_mapping()
    assert sorted(actual) == sorted(expected)
    differences = [(case, key, expected[case].get(key), actual[case].get(key))
                   for case in expected
                   for key in sorted(set(expected[case]) | set(actual[case]))
                   if expected[case].get(key) != actual[case].get(key)]
    assert not differences, differences


if __name__ == '__main__':
    if sys.argv[1:] == ['--write']:
        EXPECTED.write_text(json.dumps(decoded_mapping(), indent=1, sort_keys=True) + '\n')
    else:
        test_stream_mapping_matches_reference()
