<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>smart_rviz_plugin</name>
  <version>4.0.0</version>
  <description>TargetList Recorder</description>
  <maintainer email="shahrukh.raja@smartmicro.de">shahrukh</maintainer>
  <license>Apache 2.0 License</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  
  <build_depend condition="$ROS_DISTRO == 'foxy' or $ROS_DISTRO == 'humble' or $ROS_DISTRO == 'iron' or $ROS_DISTRO == 'jazzy' or $ROS_DISTRO == 'kilted'">qtbase5-dev</build_depend>
  <build_depend condition="$ROS_DISTRO == 'lyrical' or $ROS_DISTRO == 'rolling'">qt6-base-dev</build_depend>

  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rcl_interfaces</depend>
  <depend>umrr_ros2_msgs</depend>
  <depend>resource_retriever</depend>
  <depend>rviz_common</depend>
  <depend>rviz_default_plugins</depend>
  <depend>rviz_ogre_vendor</depend>
  <depend>rviz_rendering</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>libopencv-dev</depend>
  
  <exec_depend>xacro</exec_depend>
  <exec_depend>rviz2</exec_depend>
  
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_test</test_depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
