#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Generate a probe program that runs the stream codecs on mocked SDK lists.

Every SDK getter of a mocked class returns a distinct small integer, so the
probe output shows which getter fills each message and point field. Usage:
generate_probe.py <sdk include dir> <sensor_model_traits.hpp> <out.cpp> <codes.json>
"""

import json
import os
import re
import sys

# Stream kind -> (traits flag, SDK sub-namespace, list class, codec call).
STREAMS = {
    'port_targets': ('', 'comtargetlist', 'ComTargetList'),
    'port_objects': ('kPortObjects', 'comobjectlist', 'ComObjectList'),
    'fault_reports': ('kFaultReports', 'faultreports', 'FaultReports'),
    'can_targets': ('kCanTargets', 'comtargetbaselist', 'ComTargetBaseList'),
    'can_objects': ('kCanObjects', 'comobjectbaselist', 'ComObjectBaseList'),
}
ROLE_BASE = {'list': 0, 'port_header': 32, 'list_header': 64, 'item': 96}
PORT_HEADERS = ('PortHeader', 'GenericPortHeader')
VERSIONED = [('uint16_t', 'GetMajorVer'), ('uint16_t', 'GetMinorVer'), ('uint16_t', 'GetPatchVer')]


def parse_class(path):
    text = open(path).read()
    base = re.search(r'class\s+(?:\w+\s+)?\w+\s*:\s*public\s+([\w:]+)', text).group(1)
    methods = re.findall(r'virtual\s+(.+?)\s*(\bGet\w+)\(\)\s*const\s*=\s*0', text)
    methods = [(ret.strip(), name) for ret, name in methods]
    return methods + (VERSIONED if 'VersionedIface' in base else [])


class Generator:

    def __init__(self, include):
        self.include = include
        self.mocks = {}
        self.codes = {}

    def mock(self, ns, sub, cls, role):
        key = f'{ns}/{sub}/{cls}'
        name = f'Mock_{ns}_{sub}_{cls}'
        if key in self.mocks:
            return name
        qualified = f'com::master::{ns}::{sub}'
        lines, members, codes = [], [], {}
        for ret, getter in parse_class(os.path.join(self.include, ns, sub, cls + '.h')):
            compact = ret.replace(' ', '')
            pointer = re.match(r'std::shared_ptr<(\w+)>$', compact)
            vector = re.match(r'conststd::vector<std::shared_ptr<(\w+)>>&$', compact)
            if pointer:
                child = pointer.group(1)
                child_mock = self.mock(
                    ns, sub, child, 'port_header' if child in PORT_HEADERS else 'list_header')
                members.append(f'  std::shared_ptr<{child_mock}> m_{getter}{{'
                               f'std::make_shared<{child_mock}>()}};')
                lines.append(f'  std::shared_ptr<{qualified}::{child}> {getter}() const override'
                             f' {{return m_{getter};}}')
            elif vector:
                child = vector.group(1)
                child_mock = self.mock(ns, sub, child, 'item')
                members.append(f'  std::vector<std::shared_ptr<{qualified}::{child}>> m_{getter}{{'
                               f'std::make_shared<{child_mock}>(), '
                               f'std::make_shared<{child_mock}>()}};')
                lines.append(f'  const std::vector<std::shared_ptr<{qualified}::{child}>> & '
                             f'{getter}() const override {{return m_{getter};}}')
            else:
                code = ROLE_BASE[role] + len(codes) + 1
                assert len(codes) < 31, key
                codes[getter] = code
                lines.append(f'  {ret} {getter}() const override '
                             f'{{return static_cast<{ret}>({code});}}')
        self.codes[key] = {'role': role, 'codes': codes}
        self.mocks[key] = '\n'.join(
            [f'class {name} : public {qualified}::{cls}', '{', 'public:'] + lines + members +
            ['};', ''])
        return name


CODECS = {
    'port_targets': ('umrr_ros2_msgs::msg::PortTargetHeader', 'RadarCloudBuilder',
                     'codec::convert_port_targets<models::{traits}::kTargetOptions>'
                     '(list, header, cloud, &raw);'),
    'port_objects': ('umrr_ros2_msgs::msg::PortObjectHeader', 'ObjectCloudBuilder',
                     'codec::convert_port_objects(list, header, cloud);'),
    'fault_reports': ('umrr_ros2_msgs::msg::PortFaultReportsMsg', None,
                      'codec::convert_fault_reports(list, header);'),
    'can_targets': ('umrr_ros2_msgs::msg::CanTargetHeader', 'RadarCloudBuilder',
                    'codec::convert_can_targets(list, header, cloud);'),
    'can_objects': ('umrr_ros2_msgs::msg::CanObjectHeader', 'ObjectCloudBuilder',
                    'codec::convert_can_objects(list, header, cloud);'),
}

PROLOGUE = r"""// Generated by generate_probe.py; do not edit.
#include <umrr_ros2_driver/sensor_model_traits.hpp>

#include <cmath>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

@@MOCKS@@
using namespace smartmicro::drivers::radar;  // NOLINT

namespace
{
void dump_cloud(std::ostream & out, const sensor_msgs::msg::PointCloud2 & cloud)
{
  out << ", \"cloud\": [";
  for (uint32_t i = 0; i < cloud.width; ++i) {
    out << (i ? ", {" : "{");
    for (size_t f = 0; f < cloud.fields.size(); ++f) {
      const auto & field = cloud.fields[f];
      const uint8_t * data = cloud.data.data() + i * cloud.point_step + field.offset;
      double value = 0;
      switch (field.datatype) {
        case 7: {float v; std::memcpy(&v, data, 4); value = v; break;}
        case 6: {uint32_t v; std::memcpy(&v, data, 4); value = v; break;}
        case 4: {uint16_t v; std::memcpy(&v, data, 2); value = v; break;}
        case 3: {int16_t v; std::memcpy(&v, data, 2); value = v; break;}
        case 2: {uint8_t v; std::memcpy(&v, data, 1); value = v; break;}
        default: value = -1;
      }
      out << (f ? ", " : "") << "\"" << field.name << "\": ";
      if (std::isnan(value)) {out << "\"nan\"";} else {out << std::setprecision(17) << value;}
    }
    out << "}";
  }
  out << "]";
}
}  // namespace

int main()
{
  std::cout << "{\n";
  const char * separator = "";
"""


def main():
    include, traits_path, out_cpp, out_codes = sys.argv[1:5]
    traits_text = open(traits_path).read()
    generator = Generator(include)
    body, cases = [], {}
    for match in re.finditer(r'struct (\w+) : ModelBase<\s*com::master::(\w+)::'
                             r'DataStreamServiceIface,\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+)'
                             r'(,\s*true)?>', traits_text):
        traits, ns = match.group(1), match.group(2)
        flags = dict(zip(['kPortObjects', 'kFaultReports', 'kCanTargets', 'kCanObjects'],
                         [match.group(i) == 'true' for i in range(3, 7)]))
        for stream, (flag, sub, cls) in STREAMS.items():
            if flag and not flags[flag]:
                continue
            if stream == 'port_targets' and match.group(7):
                sub, cls = 'comtargetlistport', 'ComTargetListPort'
            mock = generator.mock(ns, sub, cls, 'list')
            header_type, builder, call = CODECS[stream]
            case = f'{traits}/{stream}'
            cases[case] = f'{ns}/{sub}'
            lines = [f'  {{  // {case}', f'    {mock} list;', f'    {header_type} header;',
                     '    sensor_msgs::msg::PointCloud2 msg;',
                     '    umrr_ros2_msgs::msg::Umrr96RawQuality raw;']
            if builder:
                lines.append(f'    {builder} cloud{{msg, "probe"}};')
            lines += [f'    {call.format(traits=traits)}', '    std::ostringstream out;',
                      '    out << "\\"header\\": " << '
                      'std::quoted(umrr_ros2_msgs::msg::to_yaml(header, true));',
                      '    out << ", \\"raw\\": " << '
                      'std::quoted(umrr_ros2_msgs::msg::to_yaml(raw, true));']
            if builder:
                lines.append('    dump_cloud(out, msg);')
            lines += [f'    std::cout << separator << "\\"{case}\\": {{" << out.str() << "}}";',
                      '    separator = ",\\n";', '  }']
            body += lines
    mocks = '\n'.join(generator.mocks.values())
    source = '\n'.join([PROLOGUE.replace('@@MOCKS@@', mocks)] + body +
                       ['  std::cout << "\\n}\\n";', '  return 0;', '}', ''])
    open(out_cpp, 'w').write(source)
    json.dump({'codes': generator.codes, 'cases': cases}, open(out_codes, 'w'), indent=1)


if __name__ == '__main__':
    main()
